- name: Configure hostname
  sudo: True
  template: >
    src=../files/hostname.j2
    dest=/etc/hostname
    owner=root
    group=root
    mode=0644

- name: Configure hosts
  sudo: True
  template: >
    src=../files/hosts.j2
    dest=/etc/hosts
    owner=root
    group=root
    mode=0644